### ISSUE TITLE
Settings file not working

### ISSUE THREAD

**Issue by CriminalPancake** [Corvimae/kaizo-ironmon-plus#1]
Randomizer settings file for Ironmon plus doesn't work, here is the error from the launcher: 
![image](https://user-images.githubusercontent.com/37886094/195506983-989983ec-e203-40b5-9934-7b7780b88110.png)

**Comment by Corvimae** [comment]
Try it on 4.4.0, I'm pretty sure that's the version that was out when I made it.

**Comment by MochiOchi** [comment]
> Try it on 4.4.0, I'm pretty sure that's the version that was out when I made it.

I've tried that and it doesn't work, same exact errors. It's almost been a year and I don't think anybody can get it to work

**Comment by Corvimae** [comment]
Resolved as of #7
