### ISSUE TITLE
Rival pokemon issues 

### ISSUE THREAD

**Issue by vitotrue** [Corvimae/kaizo-ironmon-plus#2]
the randomized levels of the rival are compleatly fucked up, they are supposed to be the 50% higher of my strongest pokemon (my pokemon is lv 5 his whould be lv 8); but somehow whene i start a new run the pokemon level of the rival is de 50% higher than the level of HIS previus starter (my pokemon is lv5 and his would be lv 12 or even higher) i don't know if this is some randomized rule error or a rom error and i don't know how to fix it
Send help

**Comment by Corvimae** [comment]
They're supposed to be 50% higher than the vanilla fight levels. This is part of [UPRZX](https://github.com/Ajarmar/universal-pokemon-randomizer-zx), not this ruleset; I can't change it, sorry!
