### ISSUE TITLE
Ironmon Rules Note / Disclaimer

### ISSUE THREAD

**Issue by UTDZac** [Corvimae/kaizo-ironmon-plus#8]
Hi,

I wanted to put in a request to add in a notice at the top of your rules doc letting people know this is a modified version of the Ironmon Ruleset.

At current, searching Google for "ironmon rules" or "kaizo ironmon" shows this github rules page as the top result. Many people new to ironmon read these rules and assume they are *the* ironmon rules, but they're a modification of kaizo ironmon. It's not clear to newcomers that these are modified from the original official ruleset. There is often confusion in regular kaizo ironmon twitch chats between the rulesets, and many people who just want normal kaizo ironmon don't are playing under the wrong ruleset.

I'd like to see if it's possible to add a disclaimer at the top, to help point out that this ruleset is different from other kaizo ironmon rulesets (notably, the one from ironmon.gg)

Thanks

**Comment by Corvimae** [comment]
I've added a note to the top of `rules.md` linking to the KI+ differences section.

**Comment by Corvimae** [comment]
That said, it does look like the ironmon.gg Gist is not public, which is probably contributing to this.

**Comment by UTDZac** [comment]
Awesome thank you. Good note about the public status, I'll check into that. Appreciate it
